apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer-replicaset
  namespace: anna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-container
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/consumer_c-2024:anna
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 50m
              memory: 56Mi 
          env:
            - name: REDIS_HOST
              value: svc-redis
            - name: RABBITMQ_HOST
              value: svc-rabbitmq
