apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq-replicaset
  namespace: anna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/rabbitmq-2024:anna
          ports:
            - containerPort: 5672
            - containerPort: 15672
