apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  namespace: anna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/redis-2024:anna
          ports:
            - containerPort: 6379
