apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replicaset
  namespace: anna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <votre-image-backend> # Remplacez par l'image Docker de l'API
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: RABBITMQ_HOST
          value: rabbitmq-service

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: anna
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
