apiVersion: v1
kind: Service
metadata:
  name: svc-api
  namespace: anna
spec:
  ports:
  - port: 8080          # Port exposé par le service
    targetPort: 5000    # Port utilisé par l'application Flask dans le Pod
  selector:
    app: api            # Doit correspondre aux labels du Pod
