apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  namespace: anna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend_b-2025:anna
          ports:
            - containerPort: 8080
          
          env:
            - name: REDIS_HOST
              value: svc-redis
            - name: RABBITMQ_HOST
              value: svc-rabbitmq

#europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend_api-2024:anna
#europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-2024:anna


