# Utiliser l'image officielle de Redis comme base
FROM redis:alpine

# Copier un fichier de configuration personnalisé (si nécessaire)
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Définir la commande de démarrage
CMD ["redis-server", "--bind", "0.0.0.0"]
